services:
  db:
    image: postgres:17
    container_name: shop
    environment:
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_pass
      POSTGRES_DB: shop
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"

volumes:
  postgres_data: