import { z } from "zod";
export declare const CategorySchema: z.ZodObject<{
    id: z.ZodNumber;
    uid: z.ZodString;
    name: z.ZodString;
    slug: z.ZodString;
    description: z.ZodString;
    status: z.ZodString;
    position: z.ZodNumber;
    image_url: z.ZodNullable<z.ZodString>;
    banner_url: z.ZodNullable<z.ZodString>;
    icon_url: z.ZodNullable<z.ZodString>;
    parent_uid: z.ZodNullable<z.ZodString>;
    shop_id: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    id: number;
    name: string;
    shop_id: number;
    uid: string;
    description: string;
    status: string;
    slug: string;
    position: number;
    image_url: string | null;
    banner_url: string | null;
    icon_url: string | null;
    parent_uid: string | null;
}, {
    id: number;
    name: string;
    shop_id: number;
    uid: string;
    description: string;
    status: string;
    slug: string;
    position: number;
    image_url: string | null;
    banner_url: string | null;
    icon_url: string | null;
    parent_uid: string | null;
}>;
export declare const CategoryCreateRequestSchema: z.ZodObject<{
    name: z.ZodString;
    slug: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    image_url: z.ZodOptional<z.ZodString>;
    banner_url: z.ZodOptional<z.ZodString>;
    icon_url: z.ZodOptional<z.ZodString>;
    position: z.ZodOptional<z.ZodNumber>;
    parent_uid: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    name: string;
    slug: string;
    description?: string | undefined;
    position?: number | undefined;
    image_url?: string | undefined;
    banner_url?: string | undefined;
    icon_url?: string | undefined;
    parent_uid?: string | undefined;
}, {
    name: string;
    slug: string;
    description?: string | undefined;
    position?: number | undefined;
    image_url?: string | undefined;
    banner_url?: string | undefined;
    icon_url?: string | undefined;
    parent_uid?: string | undefined;
}>;
export declare const CategoryUpdateRequestSchema: z.ZodObject<{
    uid: z.ZodString;
    name: z.ZodOptional<z.ZodString>;
    slug: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    image_url: z.ZodOptional<z.ZodString>;
    banner_url: z.ZodOptional<z.ZodString>;
    icon_url: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodString>;
    position: z.ZodOptional<z.ZodNumber>;
    parent_uid: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    uid: string;
    name?: string | undefined;
    description?: string | undefined;
    status?: string | undefined;
    slug?: string | undefined;
    position?: number | undefined;
    image_url?: string | undefined;
    banner_url?: string | undefined;
    icon_url?: string | undefined;
    parent_uid?: string | undefined;
}, {
    uid: string;
    name?: string | undefined;
    description?: string | undefined;
    status?: string | undefined;
    slug?: string | undefined;
    position?: number | undefined;
    image_url?: string | undefined;
    banner_url?: string | undefined;
    icon_url?: string | undefined;
    parent_uid?: string | undefined;
}>;
