import { z } from "zod";
export declare const ProductSchema: z.ZodObject<{
    id: z.ZodNumber;
    uid: z.ZodString;
    name: z.ZodString;
    description: z.ZodNullable<z.ZodString>;
    category: z.ZodString;
    type: z.ZodString;
    min: z.ZodNumber;
    max: z.ZodNumber;
    position: z.ZodNumber;
    status: z.ZodString;
    stock: z.ZodNumber;
    sku: z.ZodNullable<z.ZodString>;
    image_url: z.ZodNullable<z.ZodString>;
    gallery_urls: z.ZodNullable<z.ZodArray<z.ZodString, "many">>;
    tags: z.ZodNullable<z.ZodArray<z.ZodString, "many">>;
    is_featured: z.ZodBoolean;
    brand: z.ZodNullable<z.ZodString>;
    weight: z.ZodNullable<z.ZodNumber>;
    dimensions: z.ZodNullable<z.ZodString>;
    price: z.ZodNumber;
    compare_price: z.ZodNullable<z.ZodNumber>;
    discount_type: z.ZodNullable<z.ZodString>;
    discount_value: z.ZodNullable<z.ZodNumber>;
    slug: z.ZodString;
    shop_id: z.ZodNumber;
    timestamp: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: number;
    price: number;
    name: string;
    type: string;
    category: string;
    min: number;
    max: number;
    shop_id: number;
    uid: string;
    description: string | null;
    status: string;
    slug: string;
    position: number;
    stock: number;
    sku: string | null;
    image_url: string | null;
    gallery_urls: string[] | null;
    tags: string[] | null;
    is_featured: boolean;
    brand: string | null;
    weight: number | null;
    dimensions: string | null;
    compare_price: number | null;
    discount_type: string | null;
    discount_value: number | null;
    timestamp: string;
}, {
    id: number;
    price: number;
    name: string;
    type: string;
    category: string;
    min: number;
    max: number;
    shop_id: number;
    uid: string;
    description: string | null;
    status: string;
    slug: string;
    position: number;
    stock: number;
    sku: string | null;
    image_url: string | null;
    gallery_urls: string[] | null;
    tags: string[] | null;
    is_featured: boolean;
    brand: string | null;
    weight: number | null;
    dimensions: string | null;
    compare_price: number | null;
    discount_type: string | null;
    discount_value: number | null;
    timestamp: string;
}>;
export declare const ProductPublicSchema: z.ZodObject<{
    id: z.ZodNumber;
    uid: z.ZodString;
    name: z.ZodString;
    description: z.ZodNullable<z.ZodString>;
    category: z.ZodString;
    type: z.ZodString;
    min: z.ZodNumber;
    max: z.ZodNumber;
    price: z.ZodNumber;
    status: z.ZodString;
    stock: z.ZodNumber;
    image_url: z.ZodNullable<z.ZodString>;
    gallery_urls: z.ZodNullable<z.ZodArray<z.ZodString, "many">>;
    is_featured: z.ZodBoolean;
    brand: z.ZodNullable<z.ZodString>;
    compare_price: z.ZodNullable<z.ZodNumber>;
    slug: z.ZodString;
    discount_type: z.ZodNullable<z.ZodString>;
    discount_value: z.ZodNullable<z.ZodNumber>;
    timestamp: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: number;
    price: number;
    name: string;
    type: string;
    category: string;
    min: number;
    max: number;
    uid: string;
    description: string | null;
    status: string;
    slug: string;
    stock: number;
    image_url: string | null;
    gallery_urls: string[] | null;
    is_featured: boolean;
    brand: string | null;
    compare_price: number | null;
    discount_type: string | null;
    discount_value: number | null;
    timestamp: string;
}, {
    id: number;
    price: number;
    name: string;
    type: string;
    category: string;
    min: number;
    max: number;
    uid: string;
    description: string | null;
    status: string;
    slug: string;
    stock: number;
    image_url: string | null;
    gallery_urls: string[] | null;
    is_featured: boolean;
    brand: string | null;
    compare_price: number | null;
    discount_type: string | null;
    discount_value: number | null;
    timestamp: string;
}>;
export declare const ProductCreateInputSchema: z.ZodObject<{
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    category: z.ZodString;
    type: z.ZodString;
    min: z.ZodNumber;
    max: z.ZodNumber;
    price: z.ZodNumber;
    position: z.ZodOptional<z.ZodNumber>;
    stock: z.ZodOptional<z.ZodNumber>;
    sku: z.ZodOptional<z.ZodString>;
    image_url: z.ZodOptional<z.ZodString>;
    gallery_urls: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    is_featured: z.ZodOptional<z.ZodBoolean>;
    brand: z.ZodOptional<z.ZodString>;
    weight: z.ZodOptional<z.ZodNumber>;
    dimensions: z.ZodOptional<z.ZodString>;
    slug: z.ZodString;
    compare_price: z.ZodOptional<z.ZodNumber>;
    discount_type: z.ZodOptional<z.ZodString>;
    discount_value: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    price: number;
    name: string;
    type: string;
    category: string;
    min: number;
    max: number;
    slug: string;
    description?: string | undefined;
    position?: number | undefined;
    stock?: number | undefined;
    sku?: string | undefined;
    image_url?: string | undefined;
    gallery_urls?: string[] | undefined;
    tags?: string[] | undefined;
    is_featured?: boolean | undefined;
    brand?: string | undefined;
    weight?: number | undefined;
    dimensions?: string | undefined;
    compare_price?: number | undefined;
    discount_type?: string | undefined;
    discount_value?: number | undefined;
}, {
    price: number;
    name: string;
    type: string;
    category: string;
    min: number;
    max: number;
    slug: string;
    description?: string | undefined;
    position?: number | undefined;
    stock?: number | undefined;
    sku?: string | undefined;
    image_url?: string | undefined;
    gallery_urls?: string[] | undefined;
    tags?: string[] | undefined;
    is_featured?: boolean | undefined;
    brand?: string | undefined;
    weight?: number | undefined;
    dimensions?: string | undefined;
    compare_price?: number | undefined;
    discount_type?: string | undefined;
    discount_value?: number | undefined;
}>;
export declare const ProductUpdateInputSchema: z.ZodObject<{
    uid: z.ZodString;
    name: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    category: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodString>;
    min: z.ZodOptional<z.ZodNumber>;
    max: z.ZodOptional<z.ZodNumber>;
    price: z.ZodOptional<z.ZodNumber>;
    position: z.ZodOptional<z.ZodNumber>;
    status: z.ZodOptional<z.ZodString>;
    stock: z.ZodOptional<z.ZodNumber>;
    sku: z.ZodOptional<z.ZodString>;
    image_url: z.ZodOptional<z.ZodString>;
    gallery_urls: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    is_featured: z.ZodOptional<z.ZodBoolean>;
    brand: z.ZodOptional<z.ZodString>;
    weight: z.ZodOptional<z.ZodNumber>;
    dimensions: z.ZodOptional<z.ZodString>;
    compare_price: z.ZodOptional<z.ZodNumber>;
    discount_type: z.ZodOptional<z.ZodString>;
    slug: z.ZodString;
    discount_value: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    uid: string;
    slug: string;
    price?: number | undefined;
    name?: string | undefined;
    type?: string | undefined;
    category?: string | undefined;
    min?: number | undefined;
    max?: number | undefined;
    description?: string | undefined;
    status?: string | undefined;
    position?: number | undefined;
    stock?: number | undefined;
    sku?: string | undefined;
    image_url?: string | undefined;
    gallery_urls?: string[] | undefined;
    tags?: string[] | undefined;
    is_featured?: boolean | undefined;
    brand?: string | undefined;
    weight?: number | undefined;
    dimensions?: string | undefined;
    compare_price?: number | undefined;
    discount_type?: string | undefined;
    discount_value?: number | undefined;
}, {
    uid: string;
    slug: string;
    price?: number | undefined;
    name?: string | undefined;
    type?: string | undefined;
    category?: string | undefined;
    min?: number | undefined;
    max?: number | undefined;
    description?: string | undefined;
    status?: string | undefined;
    position?: number | undefined;
    stock?: number | undefined;
    sku?: string | undefined;
    image_url?: string | undefined;
    gallery_urls?: string[] | undefined;
    tags?: string[] | undefined;
    is_featured?: boolean | undefined;
    brand?: string | undefined;
    weight?: number | undefined;
    dimensions?: string | undefined;
    compare_price?: number | undefined;
    discount_type?: string | undefined;
    discount_value?: number | undefined;
}>;
export declare const DeleteProductInputSchema: z.ZodObject<{
    uid: z.ZodString;
}, "strip", z.ZodTypeAny, {
    uid: string;
}, {
    uid: string;
}>;
export declare const DeleteMultipleProductsInputSchema: z.ZodObject<{
    uids: z.ZodArray<z.ZodString, "many">;
}, "strip", z.ZodTypeAny, {
    uids: string[];
}, {
    uids: string[];
}>;
