import { z } from "zod";
export declare const ProductPublicListResponse: {
    description: string;
    content: {
        "application/json": {
            schema: z.ZodArray<z.ZodObject<{
                id: z.ZodNumber;
                uid: z.ZodString;
                name: z.ZodString;
                description: z.ZodNullable<z.ZodString>;
                category: z.ZodString;
                type: z.ZodString;
                min: z.ZodNumber;
                max: z.ZodNumber;
                price: z.ZodNumber;
                status: z.ZodString;
                stock: z.ZodNumber;
                image_url: z.ZodNullable<z.ZodString>;
                gallery_urls: z.ZodNullable<z.ZodArray<z.ZodString, "many">>;
                is_featured: z.ZodBoolean;
                brand: z.ZodNullable<z.ZodString>;
                compare_price: z.ZodNullable<z.ZodNumber>;
                slug: z.ZodString;
                discount_type: z.ZodNullable<z.ZodString>;
                discount_value: z.ZodNullable<z.ZodNumber>;
                timestamp: z.ZodString;
            }, "strip", z.ZodTypeAny, {
                id: number;
                price: number;
                name: string;
                type: string;
                category: string;
                min: number;
                max: number;
                uid: string;
                description: string | null;
                status: string;
                slug: string;
                stock: number;
                image_url: string | null;
                gallery_urls: string[] | null;
                is_featured: boolean;
                brand: string | null;
                compare_price: number | null;
                discount_type: string | null;
                discount_value: number | null;
                timestamp: string;
            }, {
                id: number;
                price: number;
                name: string;
                type: string;
                category: string;
                min: number;
                max: number;
                uid: string;
                description: string | null;
                status: string;
                slug: string;
                stock: number;
                image_url: string | null;
                gallery_urls: string[] | null;
                is_featured: boolean;
                brand: string | null;
                compare_price: number | null;
                discount_type: string | null;
                discount_value: number | null;
                timestamp: string;
            }>, "many">;
        };
    };
};
export declare const ProductListResponse: {
    description: string;
    content: {
        "application/json": {
            schema: z.ZodArray<z.ZodObject<{
                id: z.ZodNumber;
                uid: z.ZodString;
                name: z.ZodString;
                description: z.ZodNullable<z.ZodString>;
                category: z.ZodString;
                type: z.ZodString;
                min: z.ZodNumber;
                max: z.ZodNumber;
                position: z.ZodNumber;
                status: z.ZodString;
                stock: z.ZodNumber;
                sku: z.ZodNullable<z.ZodString>;
                image_url: z.ZodNullable<z.ZodString>;
                gallery_urls: z.ZodNullable<z.ZodArray<z.ZodString, "many">>;
                tags: z.ZodNullable<z.ZodArray<z.ZodString, "many">>;
                is_featured: z.ZodBoolean;
                brand: z.ZodNullable<z.ZodString>;
                weight: z.ZodNullable<z.ZodNumber>;
                dimensions: z.ZodNullable<z.ZodString>;
                price: z.ZodNumber;
                compare_price: z.ZodNullable<z.ZodNumber>;
                discount_type: z.ZodNullable<z.ZodString>;
                discount_value: z.ZodNullable<z.ZodNumber>;
                slug: z.ZodString;
                shop_id: z.ZodNumber;
                timestamp: z.ZodString;
            }, "strip", z.ZodTypeAny, {
                id: number;
                price: number;
                name: string;
                type: string;
                category: string;
                min: number;
                max: number;
                shop_id: number;
                uid: string;
                description: string | null;
                status: string;
                slug: string;
                position: number;
                stock: number;
                sku: string | null;
                image_url: string | null;
                gallery_urls: string[] | null;
                tags: string[] | null;
                is_featured: boolean;
                brand: string | null;
                weight: number | null;
                dimensions: string | null;
                compare_price: number | null;
                discount_type: string | null;
                discount_value: number | null;
                timestamp: string;
            }, {
                id: number;
                price: number;
                name: string;
                type: string;
                category: string;
                min: number;
                max: number;
                shop_id: number;
                uid: string;
                description: string | null;
                status: string;
                slug: string;
                position: number;
                stock: number;
                sku: string | null;
                image_url: string | null;
                gallery_urls: string[] | null;
                tags: string[] | null;
                is_featured: boolean;
                brand: string | null;
                weight: number | null;
                dimensions: string | null;
                compare_price: number | null;
                discount_type: string | null;
                discount_value: number | null;
                timestamp: string;
            }>, "many">;
        };
    };
};
export declare const SingleProductResponse: {
    description: string;
    content: {
        "application/json": {
            schema: z.ZodObject<{
                service: z.ZodObject<{
                    id: z.ZodNumber;
                    uid: z.ZodString;
                    name: z.ZodString;
                    description: z.ZodNullable<z.ZodString>;
                    category: z.ZodString;
                    type: z.ZodString;
                    min: z.ZodNumber;
                    max: z.ZodNumber;
                    position: z.ZodNumber;
                    status: z.ZodString;
                    stock: z.ZodNumber;
                    sku: z.ZodNullable<z.ZodString>;
                    image_url: z.ZodNullable<z.ZodString>;
                    gallery_urls: z.ZodNullable<z.ZodArray<z.ZodString, "many">>;
                    tags: z.ZodNullable<z.ZodArray<z.ZodString, "many">>;
                    is_featured: z.ZodBoolean;
                    brand: z.ZodNullable<z.ZodString>;
                    weight: z.ZodNullable<z.ZodNumber>;
                    dimensions: z.ZodNullable<z.ZodString>;
                    price: z.ZodNumber;
                    compare_price: z.ZodNullable<z.ZodNumber>;
                    discount_type: z.ZodNullable<z.ZodString>;
                    discount_value: z.ZodNullable<z.ZodNumber>;
                    slug: z.ZodString;
                    shop_id: z.ZodNumber;
                    timestamp: z.ZodString;
                }, "strip", z.ZodTypeAny, {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    shop_id: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    position: number;
                    stock: number;
                    sku: string | null;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    tags: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    weight: number | null;
                    dimensions: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                }, {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    shop_id: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    position: number;
                    stock: number;
                    sku: string | null;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    tags: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    weight: number | null;
                    dimensions: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                }>;
            }, "strip", z.ZodTypeAny, {
                service: {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    shop_id: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    position: number;
                    stock: number;
                    sku: string | null;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    tags: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    weight: number | null;
                    dimensions: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                };
            }, {
                service: {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    shop_id: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    position: number;
                    stock: number;
                    sku: string | null;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    tags: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    weight: number | null;
                    dimensions: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                };
            }>;
        };
    };
};
export declare const SingleProductPublicResponse: {
    description: string;
    content: {
        "application/json": {
            schema: z.ZodObject<{
                service: z.ZodObject<{
                    id: z.ZodNumber;
                    uid: z.ZodString;
                    name: z.ZodString;
                    description: z.ZodNullable<z.ZodString>;
                    category: z.ZodString;
                    type: z.ZodString;
                    min: z.ZodNumber;
                    max: z.ZodNumber;
                    price: z.ZodNumber;
                    status: z.ZodString;
                    stock: z.ZodNumber;
                    image_url: z.ZodNullable<z.ZodString>;
                    gallery_urls: z.ZodNullable<z.ZodArray<z.ZodString, "many">>;
                    is_featured: z.ZodBoolean;
                    brand: z.ZodNullable<z.ZodString>;
                    compare_price: z.ZodNullable<z.ZodNumber>;
                    slug: z.ZodString;
                    discount_type: z.ZodNullable<z.ZodString>;
                    discount_value: z.ZodNullable<z.ZodNumber>;
                    timestamp: z.ZodString;
                }, "strip", z.ZodTypeAny, {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    stock: number;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                }, {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    stock: number;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                }>;
            }, "strip", z.ZodTypeAny, {
                service: {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    stock: number;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                };
            }, {
                service: {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    stock: number;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                };
            }>;
        };
    };
};
export declare const ProductCreated: {
    description: string;
    content: {
        "application/json": {
            schema: z.ZodObject<{
                success: z.ZodLiteral<"Product added successfully.">;
                service: z.ZodObject<{
                    id: z.ZodNumber;
                    uid: z.ZodString;
                    name: z.ZodString;
                    description: z.ZodNullable<z.ZodString>;
                    category: z.ZodString;
                    type: z.ZodString;
                    min: z.ZodNumber;
                    max: z.ZodNumber;
                    position: z.ZodNumber;
                    status: z.ZodString;
                    stock: z.ZodNumber;
                    sku: z.ZodNullable<z.ZodString>;
                    image_url: z.ZodNullable<z.ZodString>;
                    gallery_urls: z.ZodNullable<z.ZodArray<z.ZodString, "many">>;
                    tags: z.ZodNullable<z.ZodArray<z.ZodString, "many">>;
                    is_featured: z.ZodBoolean;
                    brand: z.ZodNullable<z.ZodString>;
                    weight: z.ZodNullable<z.ZodNumber>;
                    dimensions: z.ZodNullable<z.ZodString>;
                    price: z.ZodNumber;
                    compare_price: z.ZodNullable<z.ZodNumber>;
                    discount_type: z.ZodNullable<z.ZodString>;
                    discount_value: z.ZodNullable<z.ZodNumber>;
                    slug: z.ZodString;
                    shop_id: z.ZodNumber;
                    timestamp: z.ZodString;
                }, "strip", z.ZodTypeAny, {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    shop_id: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    position: number;
                    stock: number;
                    sku: string | null;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    tags: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    weight: number | null;
                    dimensions: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                }, {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    shop_id: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    position: number;
                    stock: number;
                    sku: string | null;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    tags: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    weight: number | null;
                    dimensions: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                }>;
            }, "strip", z.ZodTypeAny, {
                success: "Product added successfully.";
                service: {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    shop_id: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    position: number;
                    stock: number;
                    sku: string | null;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    tags: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    weight: number | null;
                    dimensions: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                };
            }, {
                success: "Product added successfully.";
                service: {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    shop_id: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    position: number;
                    stock: number;
                    sku: string | null;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    tags: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    weight: number | null;
                    dimensions: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                };
            }>;
        };
    };
};
export declare const ProductDeleted: {
    description: string;
    content: {
        "application/json": {
            schema: z.ZodObject<{
                success: z.ZodLiteral<"Product deleted successfully.">;
            }, "strip", z.ZodTypeAny, {
                success: "Product deleted successfully.";
            }, {
                success: "Product deleted successfully.";
            }>;
        };
    };
};
export declare const ProductsDeleted: {
    description: string;
    content: {
        "application/json": {
            schema: z.ZodObject<{
                success: z.ZodLiteral<"Products deleted successfully.">;
            }, "strip", z.ZodTypeAny, {
                success: "Products deleted successfully.";
            }, {
                success: "Products deleted successfully.";
            }>;
        };
    };
};
export declare const ProductUpdated: {
    description: string;
    content: {
        "application/json": {
            schema: z.ZodObject<{
                success: z.ZodLiteral<"Product updated successfully.">;
                service: z.ZodObject<{
                    id: z.ZodNumber;
                    uid: z.ZodString;
                    name: z.ZodString;
                    description: z.ZodNullable<z.ZodString>;
                    category: z.ZodString;
                    type: z.ZodString;
                    min: z.ZodNumber;
                    max: z.ZodNumber;
                    position: z.ZodNumber;
                    status: z.ZodString;
                    stock: z.ZodNumber;
                    sku: z.ZodNullable<z.ZodString>;
                    image_url: z.ZodNullable<z.ZodString>;
                    gallery_urls: z.ZodNullable<z.ZodArray<z.ZodString, "many">>;
                    tags: z.ZodNullable<z.ZodArray<z.ZodString, "many">>;
                    is_featured: z.ZodBoolean;
                    brand: z.ZodNullable<z.ZodString>;
                    weight: z.ZodNullable<z.ZodNumber>;
                    dimensions: z.ZodNullable<z.ZodString>;
                    price: z.ZodNumber;
                    compare_price: z.ZodNullable<z.ZodNumber>;
                    discount_type: z.ZodNullable<z.ZodString>;
                    discount_value: z.ZodNullable<z.ZodNumber>;
                    slug: z.ZodString;
                    shop_id: z.ZodNumber;
                    timestamp: z.ZodString;
                }, "strip", z.ZodTypeAny, {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    shop_id: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    position: number;
                    stock: number;
                    sku: string | null;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    tags: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    weight: number | null;
                    dimensions: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                }, {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    shop_id: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    position: number;
                    stock: number;
                    sku: string | null;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    tags: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    weight: number | null;
                    dimensions: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                }>;
            }, "strip", z.ZodTypeAny, {
                success: "Product updated successfully.";
                service: {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    shop_id: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    position: number;
                    stock: number;
                    sku: string | null;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    tags: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    weight: number | null;
                    dimensions: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                };
            }, {
                success: "Product updated successfully.";
                service: {
                    id: number;
                    price: number;
                    name: string;
                    type: string;
                    category: string;
                    min: number;
                    max: number;
                    shop_id: number;
                    uid: string;
                    description: string | null;
                    status: string;
                    slug: string;
                    position: number;
                    stock: number;
                    sku: string | null;
                    image_url: string | null;
                    gallery_urls: string[] | null;
                    tags: string[] | null;
                    is_featured: boolean;
                    brand: string | null;
                    weight: number | null;
                    dimensions: string | null;
                    compare_price: number | null;
                    discount_type: string | null;
                    discount_value: number | null;
                    timestamp: string;
                };
            }>;
        };
    };
};
